services:
  tomcat:
    container_name: tomcat
    image: tomcat:8.0.53
    hostname: tomcat
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /opt/docker/tomcat/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
      - /opt/docker/tomcat/manager.xml:/opt/tomcat/conf/Catalina/localhost/manager.xml
