services:
  tomcat:
    container_name: tomcat
    image: tomcat:9.0.88
    hostname: tomcat
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ${PWD}/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
      - ${PWD}/manager.xml:/opt/tomcat/conf/Catalina/localhost/manager.xml
