services:
  tomcat:
    container_name: tomcat
    image: tomcat:$Version
    hostname: tomcat
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /opt/docker/tomcat/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml
      - /opt/docker/tomcat/manager.xml:/opt/tomcat/conf/Catalina/localhost/manager.xml
    networks:
      - net_prd

networks:
  net_prd:
    name: net_prd
    external: true
