FROM alpine:3.16
LABEL maintainer="Andre Sartori <aph@aph.dev.br>"
RUN apk add --no-cache openjdk8-jre curl
WORKDIR /opt
RUN curl -O https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz
RUN tar zxvf apache*.tar.gz && rm apache*.tar.gz
RUN ln -s apache* tomcat
RUN mv /opt/tomcat/webapps /opt/tomcat/webapps.dist
RUN mkdir -p /opt/tomcat/webapps/ROOT
WORKDIR /opt/tomcat
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh","run"]
